name: rounded_path_builder
description: A Flutter utility to create rounded polygon paths from a list of points.
version: 0.0.1
homepage: https://github.com/LOCKEDFILE/rounded_path_builder

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
